//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficOptimizerUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrafficOptimizerUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadmiarowy czas.
        /// </summary>
        internal static string AdditionalTimeEvaluator {
            get {
                return ResourceManager.GetString("AdditionalTimeEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model zaawansowany.
        /// </summary>
        internal static string AdvancedModel {
            get {
                return ResourceManager.GetString("AdvancedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średni czas.
        /// </summary>
        internal static string AvgTimeEvaluator {
            get {
                return ResourceManager.GetString("AvgTimeEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się uzykać rezultatu optymalizacji.
        /// </summary>
        internal static string CantGetErrCode {
            get {
                return ResourceManager.GetString("CantGetErrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się odczytać postępu optymalizacji.
        /// </summary>
        internal static string CantGetProgress {
            get {
                return ResourceManager.GetString("CantGetProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się załadować optymalizacji.
        /// </summary>
        internal static string CantLoadOptimization {
            get {
                return ResourceManager.GetString("CantLoadOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się wstrzymać optymalizacji.
        /// </summary>
        internal static string CantPause {
            get {
                return ResourceManager.GetString("CantPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się wznowić optymalizacji.
        /// </summary>
        internal static string CantPlay {
            get {
                return ResourceManager.GetString("CantPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się odczytać pliku.
        /// </summary>
        internal static string CantReadResult {
            get {
                return ResourceManager.GetString("CantReadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zapisać aktualnego wyniku.
        /// </summary>
        internal static string CantSaveCurrResult {
            get {
                return ResourceManager.GetString("CantSaveCurrResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zatrzymać optymalizacji.
        /// </summary>
        internal static string CantStop {
            get {
                return ResourceManager.GetString("CantStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optymalizacja: .
        /// </summary>
        internal static string CurrentOptimizationModel {
            get {
                return ResourceManager.GetString("CurrentOptimizationModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagana lista elementów nie zawiera żadnego.
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się ustawić kodu błędu.
        /// </summary>
        internal static string ErrCodeNotSet {
            get {
                return ResourceManager.GetString("ErrCodeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się zapisać wyniku optymalizacji.
        /// </summary>
        internal static string ErrCodeSaveErr {
            get {
                return ResourceManager.GetString("ErrCodeSaveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił niespodziewany błąd podczas optymalizacji.
        /// </summary>
        internal static string ErrCodeUnexpErr {
            get {
                return ResourceManager.GetString("ErrCodeUnexpErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się sprawdzić czy optymalizacja została zakończona.
        /// </summary>
        internal static string ErrIsFinished {
            get {
                return ResourceManager.GetString("ErrIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pole nie może być puste.
        /// </summary>
        internal static string ErrObligatoryField {
            get {
                return ResourceManager.GetString("ErrObligatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod błędu.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd wystąpił w lini.
        /// </summary>
        internal static string ErrorLine {
            get {
                return ResourceManager.GetString("ErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas uruchamiania optymalizacji wystąpił błąd.
        /// </summary>
        internal static string ErrPrepareOptimization {
            get {
                return ResourceManager.GetString("ErrPrepareOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas optymalizacji wystąpił błąd.
        /// </summary>
        internal static string ErrRunOptimization {
            get {
                return ResourceManager.GetString("ErrRunOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewłaściwa wartość.
        /// </summary>
        internal static string ErrWrongValue {
            get {
                return ResourceManager.GetString("ErrWrongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generacja.
        /// </summary>
        internal static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcja &lt;green&gt; lub &lt;red&gt; nie została znaleziona.
        /// </summary>
        internal static string GreenAndRedNotSpecified {
            get {
                return ResourceManager.GetString("GreenAndRedNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzin.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik jest w złym formacie.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasa jest nieprawidłowa.
        /// </summary>
        internal static string InvalidRoute {
            get {
                return ResourceManager.GetString("InvalidRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Światła zostały zdefiniowane w innym systemie świateł.
        /// </summary>
        internal static string LightsFromOtherSystem {
            get {
                return ResourceManager.GetString("LightsFromOtherSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Światła nie mogą być zielone i czerwone jednocześnie.
        /// </summary>
        internal static string LightsInGreenAndRed {
            get {
                return ResourceManager.GetString("LightsInGreenAndRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSHADE.
        /// </summary>
        internal static string LSHADE {
            get {
                return ResourceManager.GetString("LSHADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSHADEWGD.
        /// </summary>
        internal static string LSHADEWGD {
            get {
                return ResourceManager.GetString("LSHADEWGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minut.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagany atrybut nie został znaleziony.
        /// </summary>
        internal static string MissingAttribute {
            get {
                return ResourceManager.GetString("MissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator nie jest unikatowy.
        /// </summary>
        internal static string NonUnqId {
            get {
                return ResourceManager.GetString("NonUnqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma takich świateł.
        /// </summary>
        internal static string NoSuchLights {
            get {
                return ResourceManager.GetString("NoSuchLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element do którego wystąpiło odwołanie nie istnieje.
        /// </summary>
        internal static string NoSuchReferencedItem {
            get {
                return ResourceManager.GetString("NoSuchReferencedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wszystkie światła z danego systemu świateł zostały umieszczone w grupie świateł.
        /// </summary>
        internal static string NotAllLightsInGroup {
            get {
                return ResourceManager.GetString("NotAllLightsInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba ewaluacji.
        /// </summary>
        internal static string NumOfEvaluations {
            get {
                return ResourceManager.GetString("NumOfEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończono optymalizację.
        /// </summary>
        internal static string OptimizationFinished {
            get {
                return ResourceManager.GetString("OptimizationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik + statystyki.
        /// </summary>
        internal static string RecorderResultAndStats {
            get {
                return ResourceManager.GetString("RecorderResultAndStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string RecorderResultOnly {
            get {
                return ResourceManager.GetString("RecorderResultOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istnieje już odniesienie do tej drogi w innym elementcie &lt;connector&gt;.
        /// </summary>
        internal static string RoadReferencedTwice {
            get {
                return ResourceManager.GetString("RoadReferencedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wszystkie trasy są połączone z generatorem.
        /// </summary>
        internal static string RouteWithNoGenerator {
            get {
                return ResourceManager.GetString("RouteWithNoGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisano!.
        /// </summary>
        internal static string SaveCurrentResultSuccess {
            get {
                return ResourceManager.GetString("SaveCurrentResultSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sekund.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagana sekcja nie została znaleziona.
        /// </summary>
        internal static string SectionNotSpecified {
            get {
                return ResourceManager.GetString("SectionNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model uproszczony.
        /// </summary>
        internal static string SimplifiedModel {
            get {
                return ResourceManager.GetString("SimplifiedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optymalizacja nie została zakończona. Jeżeli nie chcesz utracić wyniku musisz kliknąć przycisk stop lub poczekać do zakończenia optymalizacji aby było możliwe wyłączenie programu. Jeżeli nie zależy Ci na wyniku, to możesz zakończyć optymalizację zamykając główne okno programu (menu startowe)..
        /// </summary>
        internal static string StopOptiFirst {
            get {
                return ResourceManager.GetString("StopOptiFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas [sekundy].
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istnieje przynajmniej jedna droga, która nie jest uwzględniona w żadnej trasie.
        /// </summary>
        internal static string UncoveredRoads {
            get {
                return ResourceManager.GetString("UncoveredRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieznany błąd.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrybut ma niewłaściwą wartość.
        /// </summary>
        internal static string WrongAttribute {
            get {
                return ResourceManager.GetString("WrongAttribute", resourceCulture);
            }
        }
    }
}
